# Autogenerated by Astropy-affiliated package GWSumm's setup.py on 2013-09-23 14:16:34.456289

from astropy.version_helpers import update_git_devstr, get_git_devstr

_last_generated_version = '0.0.dev'

version = update_git_devstr(_last_generated_version)
githash = get_git_devstr(sha=True, show_warning=False)

major = 0
minor = 0
bugfix = 0

release = False
debug = False

try:
    from .utils._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
