# -----------------------
#
# Run a full build-and-test from the git repo
# using uv to install all dependencies.
#
# This is the 'full' test suite.
#
# -----------------------

name: Build and test

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS
          - Ubuntu
        python-version:
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Package list
      run: uv pip list

    - name: Run test suite
      run: uv run  -m pytest -ra --color yes --cov gwsumm --pyargs gwsumm --cov-report=xml --junitxml=pytest.xml

    - name: Test command-line interfaces
      run: |
        uv run -m coverage run --append --source gwsumm -m gwsumm --help
        uv run -m coverage run --append --source gwsumm -m gwsumm day --help
        uv run -m coverage run --append --source gwsumm -m gwsumm week --help
        uv run -m coverage run --append --source gwsumm -m gwsumm month --help
        uv run -m coverage run --append --source gwsumm -m gwsumm gps --help
        uv run -m coverage run --append --source gwsumm -m gwsumm.batch --help
        uv run -m coverage run --append --source gwsumm -m gwsumm.plot.triggers --help
        uv run -m coverage run --append --source gwsumm -m gwsumm.plot.guardian --help

    - name: Coverage report
      run: uv run -m coverage report --show-missing

    - name: Publish coverage to Codecov
      uses: codecov/codecov-action@v7.1.1
      with:
        files: coverage.xml
        flags: ${{ runner.os }}-python${{ matrix.python-version }}
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: pytest-${{ matrix.os }}-${{ matrix.python-version }}
        path: pytest.xml
